[package]
name = "teo-sql-connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teo-runtime = { path = "../teo-runtime" }
quaint-forked = { version = "0.1.3-alpha.5", features = [ "all" ] }
whoami = { version = "1.4.1" }
async-recursion = "1.0.5"
async-trait = "0.1.74"
array_tool = "1.0.3"
once_cell = "1.18"
